### ISSUE TITLE
AssertionError abruptly stops running subsequent tests

### ISSUE THREAD

**Issue by mikeytsou** [taverntesting/tavern#118]
**My test:**
``` 
  - name: Impersonate Marqeta viewer - Update self
    request:
      url: "{protocol:s}://{janus_host:s}/{update_user}/{marqeta_viewer_id}"
      method: PUT
      json:
        departments: ["Engineering"]
      headers:
        Authorization: "Basic {jwt}"
    response:
      status_code: 200
      body:
        code: 200
        message: "OK"

  - name: Impersonate Marqeta viewer - Get all users
    request:
      url: "{protocol:s}://{janus_host:s}/{get_users}"
      method: GET
      headers:
        Authorization: "Basic {jwt}"
    response:
      status_code: 200
      body:
        code: 400
        message: "Unable to get users for org - Admin or SuperAdmin role required"

  - name: Impersonate Marqeta viewer - Generate token for self
    request:
      url: "{protocol:s}://{janus_host:s}/{generate_token}"
      method: POST
      json:
        obj: {}
      headers:
        Authorization: "Basic {jwt}"
    response:
      status_code: 200
      save:
        body:
          access_token: access_token
          access_token_id: access_token_id
          application_token: application_token
```

**Output:**

```
2018-06-07 14:13:13,443 [INFO]: (tavern.core:99) Running stage : Impersonate Marqeta viewer - Update self
2018-06-07 14:13:13,614 [INFO]: (tavern.response.rest:72) Response: '<Response [200]>' ({
  "code": 400, 
  "message": "Failed to update. Requires Admin or SuperAdmin role"
}
)
2018-06-07 14:13:13,615 [DEBUG]: (tavern.response.rest:197) Nothing expected to save for body
2018-06-07 14:13:13,615 [DEBUG]: (tavern.response.rest:197) Nothing expected to save for headers
2018-06-07 14:13:13,615 [DEBUG]: (tavern.response.rest:197) Nothing expected to save for redirect_query_params
2018-06-07 14:13:13,615 [DEBUG]: (tavern.response.rest:127) No save function
2018-06-07 14:13:13,615 [DEBUG]: (tavern.response.rest:175) Validating body for {'code': 200, 'message': 'OK'}
2018-06-07 14:13:13,615 [DEBUG]: (tavern.response.base:67) expected = {'code': 200, 'message': 'OK'}, actual = {'code': 400, 'message': 'Failed to update. Requires Admin or SuperAdmin role'}
2018-06-07 14:13:13,615 [DEBUG]: (tavern.response.base:96) code: 200 vs 400
2018-06-07 14:13:13,753 [ERROR]: (tavern.response.base:101) Key mismatch on code
2018-06-07 14:13:13,753 [ERROR]: (tavern.response.base:33) Value mismatch: got '400' (type: <class 'int'>), expected '200' (type: <class 'int'>)
Traceback (most recent call last):
  File "/Users/mtsou/virtualenvs/janus/lib/python3.6/site-packages/tavern-0.7.7-py3.6.egg/tavern/util/dict_util.py", line 228, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mtsou/virtualenvs/janus/lib/python3.6/site-packages/tavern-0.7.7-py3.6.egg/tavern/response/base.py", line 99, in recurse_check_key_match
    check_keys_match_recursive(expected_val, actual_val, [])
  File "/Users/mtsou/virtualenvs/janus/lib/python3.6/site-packages/tavern-0.7.7-py3.6.egg/tavern/util/dict_util.py", line 235, in check_keys_match_recursive
    raise_from(exceptions.KeyMismatchError("Key mismatch: ({})".format(full_err())), e)
  File "/Users/mtsou/virtualenvs/janus/lib/python3.6/site-packages/future-0.16.0-py3.6.egg/future/utils/__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
tavern.util.exceptions.KeyMismatchError: Key mismatch: (expected = '200', actual = '400')
2018-06-07 14:13:13,753 [DEBUG]: (tavern.response.base:96) message: OK vs Failed to update. Requires Admin or SuperAdmin role
2018-06-07 14:13:13,754 [ERROR]: (tavern.response.base:101) Key mismatch on message
2018-06-07 14:13:13,754 [ERROR]: (tavern.response.base:33) Value mismatch: got 'Failed to update. Requires Admin or SuperAdmin role' (type: <class 'str'>), expected 'OK' (type: <class 'str'>)
Traceback (most recent call last):
  File "/Users/mtsou/virtualenvs/janus/lib/python3.6/site-packages/tavern-0.7.7-py3.6.egg/tavern/util/dict_util.py", line 228, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mtsou/virtualenvs/janus/lib/python3.6/site-packages/tavern-0.7.7-py3.6.egg/tavern/response/base.py", line 99, in recurse_check_key_match
    check_keys_match_recursive(expected_val, actual_val, [])
  File "/Users/mtsou/virtualenvs/janus/lib/python3.6/site-packages/tavern-0.7.7-py3.6.egg/tavern/util/dict_util.py", line 235, in check_keys_match_recursive
    raise_from(exceptions.KeyMismatchError("Key mismatch: ({})".format(full_err())), e)
  File "/Users/mtsou/virtualenvs/janus/lib/python3.6/site-packages/future-0.16.0-py3.6.egg/future/utils/__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
tavern.util.exceptions.KeyMismatchError: Key mismatch: (expected = 'OK', actual = 'Failed to update. Requires Admin or SuperAdmin role')
2018-06-07 14:13:13,754 [DEBUG]: (tavern.response.rest:175) Validating headers for {}
2018-06-07 14:13:13,754 [DEBUG]: (tavern.response.base:57) Nothing to check against
2018-06-07 14:13:13,754 [DEBUG]: (tavern.response.rest:175) Validating redirect_query_params for {}
2018-06-07 14:13:13,754 [DEBUG]: (tavern.response.base:57) Nothing to check against
2018-06-07 14:13:13,755 [ERROR]: (tavern.printer:21) FAILED: Impersonate Marqeta viewer - Update self [200]
2018-06-07 14:13:13,755 [ERROR]: (tavern.printer:22) Expected: {'requests': {'status_code': 200, 'body': {'code': 200, 'message': 'OK'}}}
```

For some reason, after "Impersonate Marqeta viewer - Update self" fails, the subsequent tests do not run. Can someone look into this and get back to me?

**Comment by Birne94** [comment]
Your first stage fails with an error as the first two log entries indicate:

```
2018-06-07 14:13:13,443 [INFO]: (tavern.core:99) Running stage : Impersonate Marqeta viewer - Update self
2018-06-07 14:13:13,614 [INFO]: (tavern.response.rest:72) Response: '<Response [200]>' ({
  "code": 400, 
  "message": "Failed to update. Requires Admin or SuperAdmin role"
}
)
```

After a stage fails, the test execution is aborted since one tests usually represents a series of dependent actions to be performed. If you want to execute all tests independently, you would move them to different tests.

You may want to have a look at this example where independent tests are given in a single test file: https://taverntesting.github.io/examples#2-testing-a-simple-server

**Comment by mikeytsou** [comment]
Great. Thank you for this information~

**Comment by michaelboulton** [comment]
Closing as this should be fixed
