### ISSUE TITLE
0.27.0+ breakes xdist if marks are present

### ISSUE THREAD

**Issue by dmivankov** [taverntesting/tavern#431]
Going from 0.26.5 to 0.27.0 (also tested 0.29.0, 0.30.0) makes
```
cat test_1.tavern.yaml 
---
# Every test file has one or more tests...
test_name: Get some fake data from the JSON placeholder API

marks:
  - a
  - b

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: Make sure we have the right ID

    # Define the request to be made...
    request:
      url: https://jsonplaceholder.typicode.com/posts/1
      method: GET

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        id: 1

pytest -n 2 test_1.tavern.yaml
```
fail with
```
==================================================================================================================== test session starts =====================================================================================================================
plugins: tavern-0.27.0, forked-1.0.2, cov-2.7.1, xdist-1.29.0
gw0 [1] / gw1 [1]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1400, in _save
INTERNALERROR>     dispatch = self._dispatch[tp]
INTERNALERROR> KeyError: <class 'tavern.util.dict_util.format_keys.<locals>.InnerFormattedString'>
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/_pytest/main.py", line 205, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/xdist/remote.py", line 71, in pytest_runtestloop
INTERNALERROR>     self.run_one_test(torun)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/xdist/remote.py", line 85, in run_one_test
INTERNALERROR>     self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/_pytest/runner.py", line 77, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/_pytest/runner.py", line 86, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/_pytest/runner.py", line 176, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/xdist/remote.py", line 114, in pytest_runtest_logreport
INTERNALERROR>     self.sendevent("testreport", data=data)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/xdist/remote.py", line 31, in sendevent
INTERNALERROR>     self.channel.send((name, kwargs))
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 729, in send
INTERNALERROR>     self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1371, in dumps_internal
INTERNALERROR>     return _Serializer().save(obj)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1389, in save
INTERNALERROR>     self._save(obj)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1407, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1494, in save_tuple
INTERNALERROR>     self._save(item)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1407, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1490, in save_dict
INTERNALERROR>     self._write_setitem(key, value)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1484, in _write_setitem
INTERNALERROR>     self._save(value)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1407, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1490, in save_dict
INTERNALERROR>     self._write_setitem(key, value)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1484, in _write_setitem
INTERNALERROR>     self._save(value)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1407, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1490, in save_dict
INTERNALERROR>     self._write_setitem(key, value)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1483, in _write_setitem
INTERNALERROR>     self._save(key)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1405, in _save
INTERNALERROR>     raise DumpError("can't serialize {}".format(tp))
INTERNALERROR> execnet.gateway_base.DumpError: can't serialize <class 'tavern.util.dict_util.format_keys.<locals>.InnerFormattedString'>
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/_pytest/main.py", line 205, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/xdist/dsession.py", line 115, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/xdist/dsession.py", line 138, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/xdist/dsession.py", line 180, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('test_1.tavern.yaml::Get some fake data from the JSON placeholder API', <WorkerController gw0>)
INTERNALERROR> assert not 'test_1.tavern.yaml::Get some fake data from the JSON placeholder API'
```
The issue is xdist plugin wants to serialize test using execnet
https://github.com/pytest-dev/execnet/blob/master/execnet/gateway_base.py#L1402 (has hardcoded list of supported types in form of save_"type.__name__")
and in tavern code there's https://github.com/taverntesting/tavern/blob/918466e2f1666deb390ba9f39e84b7cc2ecb689a/tavern/util/dict_util.py#L16
where strings are wrapped into _FormattedString to avoid double formatting
- maybe setting __name__ in _FormattedString and InnerFormattedString to str/ustr can fix it
- maybe tavern shouldn't be formatting marks
- maybe once marks are formatted they should be made strings

**Comment by dmivankov** [comment]
3fe8fa9f9d4690454c02a64c1a26a05e333e738e isn't the cause, with it reverted error is
```
INTERNALERROR> execnet.gateway_base.DumpError: can't serialize <class 'tavern.util.dict_util._FormattedString'>
```

**Comment by michaelboulton** [comment]
Regarding your first 3 points
1. The inner formatted string class is a hack to get around python 2 limitations and will be removed sometime in the next few months.
2. Marks need to be formatted to allow doing things like skipif/parametrize with variables included from other files
3. Strings are changed to the 'formatted string' class to avoid double-formatting, and it is very error prone to change that behaviour

Another possible solution would be to move the 'inner formatted string' class out to global scope and just choose one based on an isinstance check. Ideally of course dropping Python 2 entirely would solve it as well

**Comment by dmivankov** [comment]
Bit more debug info
```
test_1.tavern.yaml::Get some fake data from the JSON placeholder API       finish pytest_runtest_logstart --> [] [hook]
        finish pytest_runtest_setup --> [] [hook]
        pytest_runtest_makereport [hook]
            item: <YamlItem Get some fake data from the JSON placeholder API>
            call: <CallInfo when='setup' result: []>
        finish pytest_runtest_makereport --> <TestReport 'test_1.tavern.yaml::Get some fake data from the JSON placeholder API' when='setup' outcome='passed'> [hook]
        pytest_runtest_logreport [hook]
            report: <TestReport 'test_1.tavern.yaml::Get some fake data from the JSON placeholder API' when='setup' outcome='passed'>
          pytest_report_to_serializable [hook]
              config: <_pytest.config.Config object at 0x7fd0c2aedc18>
              report: <TestReport 'test_1.tavern.yaml::Get some fake data from the JSON placeholder API' when='setup' outcome='passed'>
          finish pytest_report_to_serializable --> [hook]
              nodeid: test_1.tavern.yaml::Get some fake data from the JSON placeholder API
              location: ('test_1.tavern.yaml', 0, '/home/divankov/cognitedata/safe-smoke/test_1.tavern.yaml::Get some fake data from the JSON placeholder API')
              keywords: {'a': 1, 'b': 1, 'safe-smoke': 1, 'test_1.tavern.yaml': 1, 'Get some fake data from the JSON placeholder API': 1}
              outcome: passed
              longrepr: None
              when: setup
              user_properties: []
              sections: []
              duration: 0.0021355152130126953
              _report_type: TestReport
[worker-gw0] sending testreport {'data': {'nodeid': 'test_1.tavern.yaml::Get some fake data from the JSON placeholder API', 'location': ('test_1.tavern.yaml', 0, '/home/divankov/cognitedata/safe-smoke/test_1.tavern.yaml::Get some fake data from the JSON placeholder API'), 'keywords': {'a': 1, 'b': 1, 'safe-smoke': 1, 'test_1.tavern.yaml': 1, 'Get some fake data from the JSON placeholder API': 1}, 'outcome': 'passed', 'longrepr': None, 'when': 'setup', 'user_properties': [], 'sections': [], 'duration': 0.0021355152130126953, '_report_type': 'TestReport', 'item_index': 0, 'worker_id': 'gw0'}}
    early skip of rewriting module: py._io.terminalwriter [assertion]
    early skip of rewriting module: unicodedata [assertion]
    pytest_internalerror [hook]
        excrepr: Traceback (most recent call last):
  File "/home/divankov/.local/share/virtualenvs/safe-smoke-9_JLah8q/lib/python3.7/site-packages/execnet/gateway_base.py", line 1400, in _save
    dispatch = self._dispatch[tp]
KeyError: <class 'tavern.util.dict_util._FormattedString'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
```
so it seems that changing anything in marks is error-prone, but here the error is in some "keywords" field where lots of stuff is mixed, should be safe to convert to str for keywords (but not sure how exactly marks end up in keywords)

**Comment by dmivankov** [comment]
So markers are supposed to go to keywords (https://github.com/RonnyPfannschmidt/pytest/commit/18b2c1aec9b7851f5490f84d02cb598e13c2f482)
- will anything break if we pass str to pytest item.add_marker? https://github.com/taverntesting/tavern/blob/918466e2f1666deb390ba9f39e84b7cc2ecb689a/tavern/testutils/pytesthook/item.py#L104
- also should add_markers use unformatted or formatted markers? Right now it's unformatted https://github.com/taverntesting/tavern/blob/54d33348942d0e6765e5b042164ca29d9fb07a83/tavern/testutils/pytesthook/file.py

**Comment by dmivankov** [comment]
If anyone encounters it here's temporary hack to be added to conftest.py
```python
from tavern.testutils.pytesthook.item import YamlItem
orig = YamlItem.add_markers
def patch_mark(mark):
   if mark.name == 'usefixtures':
        return mark
   if type(mark.name).__name__ in ["str", "ustr"]:
       return mark
   from _pytest.mark.structures import MarkDecorator, Mark
   mark = MarkDecorator(mark = Mark(str(mark.name), mark.args, mark.kwargs))
   return mark
def add_markers(self, pytest_marks):
    patched_marks = map(patch_mark, pytest_marks)
    return orig(self, patched_marks)
YamlItem.add_markers = add_markers
```
Disclaimer: it might break mark templating/formatting or pytest keyword filtering on marks
