### ISSUE TITLE
external functions in test

### ISSUE THREAD

**Issue by gJohnson84** [taverntesting/tavern#462]
Hi, I'm new to Tavern and the languages associated with it. I'm hoping someone can help me with a problem I'm having when adding a function to a test...

**sub-domain-generator.py**
```
import random

username = "tuser"
number = random.randint(1, 10000000)

def sub_domain_generator():
    sub_domain = username + str(number)
    return {
        "sub_domain": (sub_domain)
    }
```
**test_add-tenant.tavern.yaml**
```
---

test_name: it should add a tenant to the tenant service

stages:
  - name: it should return a status code of 200
    request:
      url: http://localhost:8000/api/tenants
      method: POST
      headers:
        content-type: application/json
      json: 
        $ext:
          function: sub-domain-generator:sub_domain_generator
        user:
          email: test@example.com
          full_name: Test User
          password: L9qmNDNg
          username: tuser
    response:
      status_code: 200
```

The test output is as follows:
```
ERROR    tavern.schemas.extensions:extensions.py:85 Error importing module sub_domain_generator
Traceback (most recent call last):
  File "/Users/gjohnson/Projects/test/integration/venv/lib/python3.7/site-packages/tavern/schemas/extensions.py", line 82, in import_ext_function
    module = importlib.import_module(module)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sub_domain_generator'
```
Any help will be massively appreciated!

**Comment by gJohnson84** [comment]
After running `PYTHONPATH=$PYTHONPATH/helpers/` as mentioned [here](https://github.com/taverntesting/tavern/issues/287) I'm still getting the `ModuleNotFoundError: No module named 'sub-domain-generator'` error upon running my tests.

Please see my terminal output below for more detail:
```
╭─ gjohnson  ~/Projects 
╰─ cd cat-house/test/integration
╭─ gjohnson  ~/Projects/cat-house/test/integration   feature/cat-house-test ● 
╰─ source venv/bin/activiate
source: no such file or directory: venv/bin/activiate
╭─ gjohnson  ~/Projects/cat-house/test/integration   feature/cat-house-test ● 
╰─ source venv/bin/activate
╭─ gjohnson  ~/Projects/cat-house/test/integration   feature/cat-house-test ●     venv
╰─ PYTHONPATH=$PYTHONPATH/helpers/
╭─ gjohnson  ~/Projects/cat-house/test/integration   feature/cat-house-test ●     venv
╰─ echo $PYTHONPATH
/helpers/
╭─ gjohnson  ~/Projects/cat-house/test/integration   feature/cat-house-test ●     venv
╰─ pytest
===================================================== test session starts =====================================================
platform darwin -- Python 3.7.4, pytest-4.5.0, py-1.8.0, pluggy-0.13.0
rootdir: /Users/gjohnson/Projects/cat-house/test/integration, inifile: pytest.ini, testpaths: tests
plugins: tavern-0.30.3
collected 1 item

tests/test_add-tenant.tavern.yaml F                                                                                     [100%]

========================================================== FAILURES ===========================================================
<string>:1: tavern.util.exceptions.BadSchemaError: Couldn't load sub-domain-generator:sub_domain_generator
================================================== 1 failed in 0.54 seconds ===================================================
```
Please also see a screenshot of my directory structure:
![Screenshot 2019-10-11 at 15 14 44](https://user-images.githubusercontent.com/16972107/66658724-f3422480-ec39-11e9-83d2-459308e1cab7.png)

The files remain as shown above.

Many thanks!!!

**Comment by gJohnson84** [comment]
This issue was resolved by adding `__init__.py` in both the `helpers` and `tests` directories.
