### ISSUE TITLE
Syntax error for any operation

### ISSUE THREAD

**Issue by macejiko** [taverntesting/tavern#5]
Hey. I've discovered such issue that actually blocks me to even try this app:

1. Do `pip install tavern`
2. Run `tavern-ci --help`

I got such output:
`Traceback (most recent call last):
  File "/usr/local/bin/tavern-ci", line 11, in <module>
    load_entry_point('tavern==0.1.1', 'console_scripts', 'tavern-ci')()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2769, in load_entry_point
    return ep.load()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2422, in load
    return self.resolve()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2428, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/tavern/entry.py", line 5, in <module>
    from .core import run
  File "/Library/Python/2.7/site-packages/tavern/core.py", line 6, in <module>
    from .util.loader import IncludeLoader
  File "/Library/Python/2.7/site-packages/tavern/util/loader.py", line 55
    Resolver, metaclass=LoaderMeta):
                       ^
SyntaxError: invalid syntax`

I have:
`$ python --version 
Python 2.7.10`

What to do next?

**Comment by benhowes** [comment]
Hi @macejiko, unfortunately the library needs to be installed with python 3 at the moment - we'll back port it over the next few days.

In the meantime, either uninstall and then `pip3 install tavern` or wait a few days for an update.

Really sorry about that, it should be more clear in the documentation!

**Comment by michaelboulton** [comment]
I've updated the documentation to says that we only support Python 3. Due to the fact that Python 2 is going to be unsupported officially within the next couple of years, we have no plans to make Tavern work with it.

**Comment by benhowes** [comment]
Hi, we have now added support for python 2.7 due to popular demand. It's available on pip
