### ISSUE TITLE
pytest & external function

### ISSUE THREAD

**Issue by wjblack74** [taverntesting/tavern#71]
Hello

I'm using tavern and pytest to perform a simple post request and check the response from a mock api endpoint.  I'm doing it in the below fashion using a yaml file.  Pytest works using the basic post yaml minus the items commented out with '#'.  We have a need to use the same yaml file but with an external function so to pass the response variables to another yaml file to be used in a get request.  How can a yaml file in this fashion using pytest call external functions?

-> pytest.exe post.tavern.yaml --junit-xml=./pass.xml

#post.tavern.yaml
stages:
  - name: Make sure number is returned correctly
    request:
      url: path_to_my_mock_endpoint
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 202
      body:
        #$ext:
          #function: utils:post_function
          #extra_kwargs:
            responseText: "Great job!"
            responseCode: 202
            tavernVerification: 1001

#utils.py
def post_function(response,**kwargs):
    print(kwargs)

**Comment by michaelboulton** [comment]
The external function has to be importable from python, and it won't just load files in the current directory by default. It might work if you set PYTHONPATH to include the current directory - I'm not sure how it works on windows but on linux it would be some like this `PYTHONPATH=$(pwd) pytest post.tavern.yaml ....`

**Comment by BusinessFawn** [comment]
One way to achieve this, assuming you're trying to run tests out of the same project is this:
\---Tests
    \---YamlFiles
    |   |   test_foo.tavern.yaml
    |   |   test_bar.tavern.yaml
    |   |   
    \---src
        |   util.py:my_func
        |

in test_foo.tavern.yaml:

`$ext:
        # This is a relative path to your python code
          function: Tests.YamlFiles.util:my_func`

**Comment by wjblack74** [comment]
Yes, this can be closed.  The dot notation from the root appears to be working.  Thanks all.

**Comment by kvenkat88** [comment]
> Yes, this can be closed. The dot notation from the root appears to be working. Thanks all.

When i try to access the test utils , i am getting the exception **ImportError: No module named eva_ask_test.test_utilities.helpers** . I am following the below project directory structure and i want to separate the test utility from the tests directory.Could you please help me to fix it. I am running my tests on Windows.
       
![image](https://user-images.githubusercontent.com/8400538/50152047-965f3180-02e8-11e9-8cbe-ecbf1b9367a7.png)

I want to access the test util in the yaml file like $ext: function: Ask_Eva_Test.Utils.util:helper_function.I am notable to access like this. If i try to load within the tests directory it is working.

**Exception:**
c:\python27\lib\site-packages\future\utils\__init__.py:456: BadSchemaError
------------------------------ Captured log call ------------------------------
extensions.py               50 ERROR    Error importing module eva_ask_test.test_utilities.helpers
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\tavern\schemas\extensions.py", line 47, in import_ext_function
    module = importlib.import_module(module)
  File "c:\python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named eva_ask_test.test_utilities.helpers
========================== 1 failed in 3.85 seconds ===========================

**Comment by Keri753951** [comment]
To use external function, a path need to be set first on linux, then does anyone know how to set it in windows? I got 'tavern.util.exceptions.BadSchemaError: Couldn't load utils:test_function'?
Thanks for anyone who could help to resolve this issue. 


Copied it on tavern web site.
================================================================
To make sure that Tavern can find external functions you need to make sure that it is in the Python path. For example, if utils.py is in the ‘tests’ folder, you will need to run your tests something like (on Linux):

$ PYTHONPATH=$PYTHONPATH:tests py.test tests/
================================================================
